import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
// import NavBar from '@/app/NavBar';
import { SansContext, SerifContext } from "@/app/fontcontext";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const pf_display = Playfair_Display({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SansContext.Provider value={inter}>
          <SerifContext.Provider value={pf_display}>
            {children}
          </SerifContext.Provider >
        </SansContext.Provider >
      </body >
    </html>
  );
}
